react/components/atoms/button/button.js

Small enhancements to button

---

react/components/atoms/icon/icon.js

| - | - |
| --- | --- |
| Decisions | Added new Bolt icon  |

Added new Bolt icon

---

package.json
react/components/atoms/button-tab/button-tab.js
react/components/molecules/tabs/tabs.js
react/components/molecules/tabs/tabs.stories.js

| - | - |
| --- | --- |
| Decisions | Small changes because of the new Navigation system  |

Footer changes for react-navigation and safe view compatibility

---

package.json
react/components/molecules/tabs/tabs.js

Fix problems with duplicated SafeAreaView

---

react/components/atoms/avatar/avatar.js
react/components/atoms/avatar/avatar.stories.js
react/components/atoms/avatar/index.js
react/components/atoms/button/button.js
react/components/atoms/index.js

| - | - |
| --- | --- |
| Decisions |  Creation avatar component |
| Animated GIF | ![Simulator Screen Shot - iPhone 11 - 2020-02-13 at 08 36 50](https://user-images.githubusercontent.com/13239857/74416022-5f2cd780-4e3c-11ea-9d4f-01e1cb90bc6a.png)|

Creation avatar component

---

react/assets/icons/index.js
react/components/atoms/icon/icon.js

| - | - |
| --- | --- |
| Issue | |
| Decisions |  Organize all the icons in an object that will be used to get the icon directly by name |

Better struture for icon use

---

react/components/atoms/tag/tag.js

| - | - |
| --- | --- |
| Issue | The component tag isn't versatile enough |
| Decisions |  Refactored the component to be more versatile |

Update Tag component to become more versatile

---

react/components/atoms/button/button.js
react/components/atoms/index.js
react/components/atoms/text/index.js
react/components/atoms/text/text.js
react/components/atoms/text/text.stories.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-react-native/issues/48 |
| Decisions | Created `Text` component  |
| Animated GIF | ![RN-Text](https://user-images.githubusercontent.com/22588915/75265927-86df5080-57e9-11ea-8a73-bf8122380485.gif) |

#48 Text component

---

react/components/atoms/index.js
react/components/atoms/link/index.js
react/components/atoms/link/link.js
react/components/atoms/link/link.stories.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-react-native/issues/37 |
| Decisions | Created `Link` component  |
| Animated GIF | ![RN-link](https://user-images.githubusercontent.com/22588915/75331275-55629580-587a-11ea-8387-7abfbd9a858e.gif) |

#37 Link component

---

react/components/atoms/index.js
react/components/atoms/textarea/index.js
react/components/atoms/textarea/textarea.js
react/components/atoms/textarea/textarea.stories.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-react-native/issues/32 |
| Decisions | Created `TextArea` component |
| Animated GIF | ![RN-Textarea](https://user-images.githubusercontent.com/22588915/75261445-f736a380-57e2-11ea-8eac-69fb6833c1e7.gif)|

#32 Textarea component

---

react/components/atoms/button-icon/button-icon.js
react/components/atoms/button-icon/button-icon.stories.js
react/components/atoms/button-icon/index.js
react/components/atoms/index.js

| - | - |
| --- | --- |
| Decisions | Creation of button icon  |
| Animated GIF | ![Feb-24-2020 10-58-43](https://user-images.githubusercontent.com/13239857/75147176-a6e11800-56f4-11ea-81d7-7957bcc9c39a.gif) |

Creation of button icon

---

react/components/atoms/avatar/avatar.js
react/components/atoms/avatar/avatar.stories.js

| - | - |
| --- | --- |
| Issue | We need to trigger some actions on avatar touch. |
| Decisions | Added touch to avatar component |
| Animated GIF | ![Feb-24-2020 15-55-28](https://user-images.githubusercontent.com/13239857/75168041-2c2cf280-571e-11ea-949b-619a55a2c0f8.gif) |

Added touch to avatar component

---

react/components/atoms/button-keyboard/button-keyboard.stories.js
react/components/atoms/button-tab/button-tab.stories.js
react/components/atoms/button/button.stories.js
react/components/atoms/icon/icon.stories.js
react/components/atoms/index.js
react/components/atoms/lightbox/index.js
react/components/atoms/lightbox/lightbox.js
react/components/atoms/lightbox/lightbox.stories.js
react/components/atoms/tag/tag.stories.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-react-native/issues/XXX |
| Decisions | Created `Lightbox` component  |
| Animated GIF | ![RN-Lightbox_1](https://user-images.githubusercontent.com/22588915/75547539-0441d580-5a23-11ea-9fac-f00b401e2f51.gif) <br>![RN-lightbox_2](https://user-images.githubusercontent.com/22588915/75547313-7ebe2580-5a22-11ea-9cb4-f9b3ecdeafb1.gif) <br>![RN-Lightbox_3](https://user-images.githubusercontent.com/22588915/75547319-84b40680-5a22-11ea-9843-3a3876a2df84.gif) |

Lightbox component

---

react/components/atoms/avatar/avatar.js

| - | - |
| --- | --- |
| Issue | Android had no border effect |
| Decisions |  Fix avatar border on android |
| Animated GIF |   ![Screenshot_1582908860](https://user-images.githubusercontent.com/13239857/75568382-13d51480-5a4b-11ea-98e1-9e1248f40220.png) ![Screenshot_1582908820](https://user-images.githubusercontent.com/13239857/75568379-133c7e00-5a4b-11ea-891f-1a62752ff801.png)|

Fix Avatar border in android

---

react/components/atoms/textarea/textarea.js

| - | - |
| --- | --- |
| Issue | - |
| Decisions | Added focus and blur capabilities to `TextArea` component |

TextArea focus and blur

---

react/components/atoms/textarea/textarea.js

| - | - |
| --- | --- |
| Issue | - |
| Decisions | Added onSubmit prop to `TextArea` component |

Added onSubmit prop to TextArea component

---

react/components/molecules/key-value/key-value.js
react/components/molecules/key-value/key-value.stories.js

| - | - |
| --- | --- |
| Issue | Increase area of touch in key value component and add longPress functionality. Related to: |
| Decisions |   |
| Animated GIF | ![](https://user-images.githubusercontent.com/24736423/75907707-ae18cc00-5e40-11ea-8330-8adb758cf3ef.gif) |

Added touchable capacity

---

react/components/atoms/textarea/textarea.js

| - | - |
| --- | --- |
| Issue | - |
| Decisions | Checked if is multiline before submitting and removed vertical padding when in multiline |

TextArea component improvements

---

react/components/atoms/bar-animated/bar-animated.js
react/components/atoms/bar-animated/bar-animated.stories.js
react/components/atoms/bar-animated/index.js
react/components/atoms/index.js

| - | - |
| --- | --- |
| Decisions | Creation of a bar with animation component  |
| Animated GIF | ![Mar-03-2020 14-31-49](https://user-images.githubusercontent.com/13239857/75786389-1bebc780-5d5d-11ea-9a19-6354febe2d7e.gif) |

Creation of Bar Animated

---

react/components/atoms/bar-animated/bar-animated.js
react/components/atoms/bar-animated/bar-animated.stories.js
react/components/atoms/bar-animated/index.js
react/components/atoms/button-tab-text/button-tab-text.js
react/components/atoms/index.js
react/components/molecules/index.js
react/components/molecules/tabs-text/index.js
react/components/molecules/tabs-text/tabs-text.js
react/components/molecules/tabs-text/tabs-text.stories.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-react-native/issues/42 |
| Dependencies | https://github.com/ripe-tech/ripe-components-react-native/pull/63 https://github.com/ripe-tech/ripe-components-react-native/pull/62 |
| Decisions | Creation of Tabs text component |
| Animated GIF | ![Mar-03-2020 14-32-38](https://user-images.githubusercontent.com/13239857/75786601-771dba00-5d5d-11ea-85a5-4f7b0d535a07.gif) a |

#42 Creation of tabs text component

---

react/components/molecules/rich-textinput/rich-textinput.js

| - | - |
| --- | --- |
| Issue | - |
| Decisions | Fixed warnings  |

Fixed warnings

---

react/components/molecules/key-value/key-value.js

Align key value with section view

---

react/components/atoms/bar-animated/bar-animated.stories.js
react/components/atoms/button-icon/button-icon.stories.js
react/components/atoms/button-tab/button-tab.stories.js

| - | - |
| --- | --- |
| Issue | - |
| Decisions | Remove previous colour picker knob used to text knob   |

Change color knobs to string instead of color picker

---

react/components/molecules/item/item.js

Item improvements

---

react/components/atoms/container-draggable/container-draggable.js
react/components/atoms/container-draggable/container-draggable.stories.js
react/components/atoms/container-draggable/index.js
react/components/atoms/container-swipeable/index.js
react/components/atoms/index.js

| - | - |
| --- | --- |
| Issue | - |
| Decisions | Renamed the component name for correct convention |

Rename contianer swipeable

---

package.json

| - | - |
| --- | --- |
| Issue | - |
| Decisions | Added "react-native-modal" dependency. |

Added "react-native-modal" dependency

---

react/components/molecules/key-value/key-value.js
react/components/molecules/key-value/key-value.stories.js

| - | - |
| --- | --- |
| Issue | - |
| Decisions | Added `keyColor` and `valueColor` props to `KeyValue` component, to be able to change the `key` and `value` colors |

KeyValue component key and value color props

---

react/components/atoms/container-openable/container-openable.js

| - | - |
| --- | --- |
| Issue | - |
| Decisions | Fix incorrect inline function call  |

Fix inline function

---

react/components/atoms/container-openable/container-openable.js
react/components/molecules/rich-textinput/rich-textinput.js
react/components/organisms/chat/chat.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/118|
| Animated GIF |![e4s72GIxM3](https://user-images.githubusercontent.com/8842023/78586147-eaba5780-7832-11ea-8b39-1f319f8ff12d.gif)|

#118: Close keyboard when closing chat.

---

react/components/molecules/key-value/key-value.js
react/components/molecules/key-values/key-values.js

| - | - |
| --- | --- |
| Issue |  |
| Animated GIF | ![image](https://user-images.githubusercontent.com/3048875/78664615-4b49a300-78cc-11ea-86fa-ee9ede460dca.png) |

Allow templating KeyValues' value

---

react/components/atoms/tag/tag.js

Remove tag border when it's transparent

---

react/components/organisms/chat/chat.js
react/components/organisms/chat/chat.stories.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-react-native/issues/129 |
| Dependencies | - |
| Decisions | - |
| Animated GIF |<img width="482" alt="imagem" src="https://user-images.githubusercontent.com/24736423/78663906-df1a6f80-78ca-11ea-98cb-5f31f7c727af.png"> |

#129 Input: app view doesn't shrink on iOS 

---

react/util/utils.js

- Change of interface is ok, no one's using it
- This new thing won't be used, but since I had to make the change to test a new UI, here it is

Optionally hide year from date text

---

react/components/molecules/index.js
react/components/molecules/key-value-placeholder/index.js
react/components/molecules/key-value-placeholder/key-value-placeholder.js
react/components/molecules/key-value-placeholder/key-value-placeholder.stories.js

| - | - |
| --- | --- |
| Issue | No issue, but necessary and part of  https://github.com/ripe-tech/ripe-robin-revamp/issues/72 |
| Dependencies | - |
| Decisions | Creation of a placeholder for Key Value component.<br> To animate this component is required the Placeholder context that can be found in https://github.com/ripe-tech/ripe-robin-revamp/pull/141 <br> This context will provide constant update of the gradient locations. |
| Animated GIF | ![Apr-13-2020 12-10-51](https://user-images.githubusercontent.com/13239857/79116236-da006900-7d7f-11ea-9c02-63f4986ecca9.gif) |

Creation of Key Value placeholder

---

react/components/molecules/index.js
react/components/molecules/key-values-placeholder/index.js
react/components/molecules/key-values-placeholder/key-values-placeholder.js
react/components/molecules/key-values-placeholder/key-values-placeholder.stories.js

| - | - |
| --- | --- |
| Issue | No issue for this pr, but is related with https://github.com/ripe-tech/ripe-robin-revamp/pull/145 |
| Dependencies | - |
| Decisions | Creation of the key values placeholder, in the same manner that we have the `keys-values` component.<br> For this component animation to work requires the `Placeholder context` provided by the main application. |
| Animated GIF | ![Apr-14-2020 12-11-27](https://user-images.githubusercontent.com/13239857/79219050-70e52800-7e49-11ea-81e6-8e721f0016fa.gif)|

Creation of key values placeholder

---

react/util/ui-utils.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/155 |
| Decisions | Identify if the device is in portrait/landscape mode and if the size is tablet/mobile. |

#155: Device Detection

---

.travis.yml
package.json

| - | - |
| --- | --- |
| Decisions | Mimic https://github.com/ripe-tech/ripe-pulse/commit/2ce0b475e2b8ec522bcb80c275c63a5f71dd5f3d |

Normalize scripts

---

react/util/ui-utils.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/214 |

fix: document picking on iOS with spaces

---

react/components/organisms/chat/chat.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/215 |

fix: send message text with attachments

---

react/components/atoms/button-tab-text/button-tab-text.js
react/components/molecules/item/item.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/240 |
| Screenshot | <img width="1217" alt="gyukyuikyui" src="https://user-images.githubusercontent.com/8842023/115218342-5f8ac780-a0fe-11eb-953c-22e73584f68a.png"> |

Text getting cropped in ios

---

CHANGELOG.md
react/components/molecules/tabs-text/tabs-text.js
react/components/molecules/tabs/tabs.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/238 |

Add selectedTabPressed events to tabs components

---

.travis.yml
package.json
react/components/organisms/chat/chat.stories.js
react/components/organisms/image-list/image-list.stories.js
react/util/ui-utils.js

| - | - |
| --- | --- |
| Decisions | the parameter removed was from a previous implementation of the function `handlePickImage` |

fix: remove dead code

---

react/util/ui-utils.js

| - | - |
| --- | --- |
| Decisions | In order scan we have a retry for permissions already. Plus, without this, users will **always** get this error unless they go settings or they accept the permissions by using order scan first. |
| Animated GIF | ![](http://g.recordit.co/oiQOQALkrS.gif) |

feat: request camera permissions on pickImage

---

react/components/atoms/avatar/avatar.js

fix: onError event handling

---

react/components/atoms/avatar/avatar.stories.js
react/components/atoms/button/button.stories.js
react/components/atoms/lightbox/lightbox.stories.js
react/components/atoms/textarea/textarea.stories.js
react/components/molecules/item/item.stories.js
react/components/molecules/rich-textinput/rich-textinput.stories.js

| - | - |
| --- | --- |
| Issue | Knobs default value as `undefined` caused this errors in storybook: ![image](https://user-images.githubusercontent.com/25725586/119647747-8ed8d680-be18-11eb-93dd-3f559d9492d3.png)|
| Decisions | Set defined values for number knobs. |

fix: storybook number knobs undefined default values error

---

react/components/atoms/lightbox/lightbox.js
react/components/atoms/textarea/textarea.js
react/components/atoms/touchable/touchable.js
react/components/molecules/item-notification/item-notification.js
react/components/organisms/image-list/image-list-item-add.js
react/components/organisms/image-list/image-list-item.js

| - | - |
| --- | --- |
| Issue | From https://github.com/ripe-tech/ripe-components-react-native/pull/179#discussion_r646607888 |

refactor: order props to variables -> funcs -> style

---

react/components/atoms/button-icon/button-icon.js
react/components/atoms/button-icon/button-icon.stories.js

| - | - |
| --- | --- |
| Issue | -- |
| Decisions | • Added missing disabled prop (already being used) <br> • Added disabled style and used opacity `0.5`, similar to other components. |

fix: added missing disabled prop and fixed style

---

CHANGELOG.md
react/components/molecules/key-values/key-values.js
react/components/molecules/key-values/key-values.stories.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/270 |
| Animated GIF | ![6XQevrVjyC](https://user-images.githubusercontent.com/8842023/124915001-ec03a280-dfe8-11eb-9fdf-c50191c53acd.gif) |

feat: add view more button in key values component

---

react/components/atoms/button/button.js
react/components/atoms/button/button.stories.js
react/components/molecules/button-toggle/button-toggle.js
react/components/molecules/button-toggle/button-toggle.stories.js
react/components/organisms/button-group/button-group.js
react/components/organisms/button-group/button-group.stories.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-id-mobile/issues/2#issuecomment-878087072 |
| Decisions | • Button variant "flat" and align support <br> • Button toggle variant, align and new directions for vertical orientation. Support for no toggle behaviour and instead call a callback function. <br> • Button toggle variant and vertical orientation. |
| Animated GIF | ![button-group-variant](https://user-images.githubusercontent.com/25725586/125437092-89e5959c-c9d6-431d-bb9e-eeb3ba567db7.gif)<br>Usage example: <br><img width="386" alt="image" src="https://user-images.githubusercontent.com/25725586/125435684-6a5ee882-0da5-48dd-b756-83f06cb4f4d5.png">|

feat: button group variant "flat" and vertical orientation

---

react/components/molecules/header/header.js

| - | - |
| --- | --- |
| Decisions | - Add missing style override prop |

Header: Add missing prop for style override

---

react/components/molecules/card/card.js

| - | - |
| --- | --- |
| Decisions | - Improve card spacing based of QA feedback. |

Card: Improve spacing

---

react/components/organisms/form/form.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-id-mobile/issues/1#issuecomment-883464734 |
| Decisions | Added padding section on end of form. |
| Animated GIF | <img width="399" alt="image" src="https://user-images.githubusercontent.com/25725586/126352989-aad95bd0-80f9-4b25-89f9-e396643b1547.png"> |

feat: add padding section on form

---

package.json

| - | - |
| --- | --- |
| Decisions | - Upgrade ripe-commons-native package to the latest https://www.npmjs.com/package/ripe-commons-native |

Bump versions: upgrade ripe-commons-native to 0.2.0

---

react/components/molecules/tabs/tabs.js

| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Fix and complete `Tabs` PropTypes. |

fix: tabs proptypes

---

package.json
react/assets/icons/calendar-round.svg
react/components/organisms/listing/listing.js

| - | - |
| --- | --- |
| Dependencies | https://github.com/ripe-tech/ripe-components-react-native/pull/233 |
| Decisions | - Implement listing `getItems`. <br> - Define filters by prop. <br>  |

#5 Listing getitems

---

CHANGELOG.md
react/components/organisms/chat/chat.js

| - | - |
| --- | --- |
| Animated GIF | ![](http://g.recordit.co/LKegQ7ysjd.gif) |

feat: avoid scroll chat when opening 1st time

---

react/components/atoms/container-openable/container-openable.js

| - | - |
| --- | --- |
| Issue |  |

feat: use linear animation in container openable component

---

CHANGELOG.md
react/util/mixins/index.js
react/util/mixins/screen.js
react/util/mixins/status-bar.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-id-mobile/pull/47#discussion_r680867702 |
| Decisions | Mixin that handles the status bar color change. |

feat: screen mixin that sets status bar color

---

CHANGELOG.md
react/components/atoms/button/button.js

| - | - |
| --- | --- |
| Issue | -- |
| Decisions | -- |

feat: support external svgs as button icons

---

react/components/molecules/keyboard/keyboard.js

| - | - |
| --- | --- |
| Decisions | - Add keyboard hide and show animations. |
https://user-images.githubusercontent.com/24736423/131837721-582f8e4f-fb12-4d2f-8c76-047e25176f43.mov

Keyboard: animations

---

CHANGELOG.md
package.json

* Added `GradientAnimated` component, which is an animated linear gradient
* ImageCarrousel 'isTabletSize' import [#284](https://github.com/ripe-tech/ripe-components-react-native/pull/284)

version: 0.12.0

---

CHANGELOG.md
react/components/atoms/lightbox/lightbox.js

| - | - |
| --- | --- |
| Issue | Related to using lightbox in card order |
| Decisions | -- |

fix: Lightbox image style prop

---

CHANGELOG.md
react/components/atoms/lightbox/lightbox.js

| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Added `source` prop to `lightbox`. |

feat: added `source` prop to lightbox 

---

CHANGELOG.md
package.json

* Bumped dependencies and dropped support for Node 10

version: 0.18.0

---

CHANGELOG.md
react/components/organisms/profile/profile.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-id-mobile/issues/58 |
| Decisions | - Unify profile approaches (there was basically a duplicate of this component in the `user-view` in `ripe-id-mobile`), allowing actions for certain key-values and using the same design in the header. |
| Animated GIF | Robin:<br><img width="531" alt="imagem" src="https://user-images.githubusercontent.com/25725586/155182168-8d5825a9-0255-448a-99d7-26e2f7c9112c.png"><br>Ripe ID Mobile:<br><img width="528" alt="imagem" src="https://user-images.githubusercontent.com/25725586/155182209-c3024d77-0f80-44c3-8057-ddc5e0c99917.png"><br><img width="536" alt="imagem" src="https://user-images.githubusercontent.com/25725586/155182326-1e1ef3e2-56bd-4ac2-b009-9e4824faa6c6.png">|

feat: unify profile component and allow action for key values

---

CHANGELOG.md
react/components/molecules/avatar-list/avatar-list.stories.js
react/components/molecules/search/search.js
react/components/molecules/select/select.js
react/components/molecules/select/select.stories.js
react/components/organisms/listing/listing.js
react/components/organisms/listing/listing.stories.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/329 |
| Decisions | Add extra style props to control the position of the input search component and filters. Add the layout variants "horizontal" and "vertical". Add expandable search bar animation. |
| Animated GIF |  ![listing](https://user-images.githubusercontent.com/16060539/161088688-37990de4-6487-4a94-a58d-ffbb2bcc6ff5.gif) |

feat: more style props for listing

---

CHANGELOG.md
package.json

version: 0.21.0

---

CHANGELOG.md
react/components/organisms/chat/chat.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/346 |
| Decisions | - add `renderBeforeMessages` prop to `Chat` component after @ConstancaCosta suggestion |

#346 Chat: Add `renderBeforeMessages` prop

---

CHANGELOG.md
react/components/molecules/tabs/tabs.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/pull/355#issuecomment-1092583546 |
| Decisions | - Add visibility toggling via tab options. |

Tabs: Visibility toggling via tab options

---

CHANGELOG.md
package.json

* Allow gesture movements on the whole container of `ContainerOpenable`, controllable by prop
* Prop that controls if the `ContainerOpenable` closes on tap

version: 0.23.0

---

CHANGELOG.md
react/components/molecules/toast-message/toast-message.js

| - | - |
| --- | --- |
| Decisions | - Add text style prop to allow better control of toast style. |

ToastMessage: Add `textStyle` prop

---

CHANGELOG.md
react/components/molecules/search/search.js

| - | - |
| --- | --- |
| Issue | Mismatch with the design, search component now has a border: <br>![image](https://user-images.githubusercontent.com/25725586/166438821-2ce05475-1ac5-4921-91db-7a098b09ad92.png)|
| Decisions | Add border to search component|
| Animated GIF | ![image](https://user-images.githubusercontent.com/25725586/166438757-b7353abf-f500-4c2c-94a9-75703d87291c.png)|

feat: add border to search component

---

CHANGELOG.md
react/components/molecules/key-values/key-values.js
react/components/molecules/tabs/tabs.js
react/components/organisms/profile/profile.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/372 |
| Decisions | -  Add more component styling props to allow theme overriding the default color scheme. |

#372 Add more component styling props

---

CHANGELOG.md
react/components/organisms/profile/profile.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/392 |
| Decisions | - Adapt to latest profile buttons design |
| Animated GIF | ![image](https://user-images.githubusercontent.com/24736423/176909052-ab848c90-4cf5-47e4-a49f-860ae7416a07.png) |

#392 Profile: adapt buttons style to latest design

---

CHANGELOG.md
react/components/atoms/status-entry/status-entry.js
react/components/molecules/chat-message/chat-message.js
react/components/organisms/chat/chat.js
react/components/organisms/listing/listing.js

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/372 |
| Decisions | - Add more props to allow theme color scheme override <br> - Small adaptation to use hex color format |

#372 Add more color scheme props

---

CHANGELOG.md
package.json

* Updated volume and mute icons
* Fixed not showing none messages animation in chat component

version: 0.27.3 :rainbow: 

---

react/components/atoms/button-icon/button-icon.js
react/components/organisms/listing/listing.js

| - | - |
| --- | --- |
| Decisions | - Update loading indicator default color from blue to gray |

Change default loading indicator color to gray

---

CHANGELOG.md
package.json

* Changed default loading indicator color to gray

version: 0.27.6

---

CHANGELOG.md
react/components/organisms/listing/listing.js

| - | - |
| --- | --- |
| Decisions | - Changed the position of the loading indicator for listing |
| Animated GIF | ![Peek 2022-09-22 11-56](https://user-images.githubusercontent.com/24736423/191729125-86ef2a83-0a07-4f27-826c-32b21a3acad7.gif) |

Changed the position of the loading indicator for listing

---

CHANGELOG.md
react/assets/icons/extra/send-alt.svg
react/assets/icons/index.js
react/assets/icons/spam.svg

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/464 |
| Decisions | - Adapt icons for order status icon listing |

#464 Fix status icons

---

CHANGELOG.md
package.json

* Add sections to key-values components - [ripe-robin-revamp/#330](https://github.com/ripe-tech/ripe-robin-revamp/issues/330)
* Changed position of loading indicator for listing component
* Add send-alt icon - [ripe-robin-revamp/#464](https://github.com/ripe-tech/ripe-robin-revamp/issues/464)
* Fix spam icon with missing dot - [ripe-robin-revamp/#464](https://github.com/ripe-tech/ripe-robin-revamp/issues/464)

version: 0.27.7 :rainbow: 

---

CHANGELOG.md
package.json

* Add `attachButtonsVisibility` prop to allow hiding attach buttons

chore: version 0.28.1 :rainbow: 
