ripe-tech/ripe-components-react-native

react/components/molecules/header/header.js
| - | - |
| --- | --- |
| Issue | The back button doesn't work, this happens because the button was behind the box of the title. |
| Decisions | Apply the zIndex to style so the button can go to the top of the title to receive touch events  |
| Animated GIF |Before: ![image](https://user-images.githubusercontent.com/13239857/75173399-b6795480-5726-11ea-8442-71a6f756d3ca.png) After:![image (1)](https://user-images.githubusercontent.com/13239857/75173406-b8dbae80-5726-11ea-8fb4-738d97453e37.png)   |
=> Fix header back button

react/components/atoms/textarea/textarea.js
| - | - |
| --- | --- |
| Issue | - |
| Decisions | Fixed `TextArea` vertical padding being different in Android |
| Animated GIF | ![RN-TextArea_padding_fix](https://user-images.githubusercontent.com/22588915/75981644-d6560880-5edc-11ea-9b0a-53631f16b80b.gif) |
=> TextArea component padding fix

react/components/molecules/item/item.js
| - | - |
| --- | --- |
| Issue | Missing box shadow in item component in Android. Example: <img width="466" alt="Screenshot 2020-03-05 at 12 20 47" src="https://user-images.githubusercontent.com/25725586/75982210-f2a67500-5edd-11ea-9adc-6f558ff8255f.png">|
| Decisions | Added elevation, similar to button-keyboard. |
| Animated GIF | <img width="466" alt="Screenshot 2020-03-05 at 12 20 54" src="https://user-images.githubusercontent.com/25725586/75982228-fd610a00-5edd-11ea-8647-5b2056085318.png">|
=> Fix box-shadow/elevation of Item in Android

react/components/atoms/button-keyboard/button-keyboard.js, react/components/molecules/keyboard-numeric/keyboard-numeric.js
| - | - |
| --- | --- |
| Issue | Keyboard button `0` was not aligned with the rest of the buttons: NOTE: The red is temporary, only for the buttons to be noticeable. <img width="466" alt="Screenshot 2020-03-05 at 12 20 54" src="https://user-images.githubusercontent.com/25725586/75983663-d1935380-5ee0-11ea-96b9-abffe5399bc8.png"> <img width="467" alt="Screenshot 2020-03-05 at 12 55 09" src="https://user-images.githubusercontent.com/25725586/75983676-d952f800-5ee0-11ea-98bb-d126b4762b7b.png"> |
| Decisions | Added marginHorizontal to filler, so that it occupies the same width as a numeric button. |
| Animated GIF | <img width="460" alt="Screenshot 2020-03-05 at 12 54 57" src="https://user-images.githubusercontent.com/25725586/75983712-ecfe5e80-5ee0-11ea-99da-46803e8b0a7f.png"> |
=> Fix keyboard alignment

react/util/ui-utils.js
| - | - |
| --- | --- |
| Issue | When camera is not authorized and in `image-list` component we click to "Add photo" and select "Take photo...", a warning of rejected promise is thrown and the user is not notified that he needs to give camera permissions in settings.  |
| Environment | This is only reproducible for **iOS**. In Android the OS takes care of letting the user know that he needs to give the right permissions and Android already shows it's own dialog for this. |
| Decisions | - |
| Animated GIF |  ![IMG_F1C3E3801513-1](https://user-images.githubusercontent.com/24736423/76312608-51e3fb00-62cb-11ea-9dcc-48c0631c045f.jpeg) |
=> Fix add image list camera authorization error handler func

react/components/atoms/button-icon/button-icon.js, react/components/atoms/button-icon/button-icon.stories.js
| - | - |
| --- | --- |
| Issue | Storybook knob number function doesn't give the correct initial value |
| Decisions | Add the prop default of `size` property in `button-icon` |
| Animated GIF | -  |
=> Fix button icon error with storybook

react/components/molecules/tabs-text/tabs-text.js
| - | - |
| --- | --- |
| Issue | Tabs text crash the app in a random manner, because we are trying to search a key in the `tabLayout` object that doesn't exist (race condition problem) |
| Decisions |  Verify if the object key exist before trying to use it |
=> Fix error in bug tabs text

react/components/molecules/item/item.js
| - | - |
| --- | --- |
| Issue | Currently the prop `headerDate`is not being applied. This PR fixes this and formats the timestamp using `dateTimeString` from utils |
| Decisions |   |
| Animated GIF | <img width="410" alt="imagem" src="https://user-images.githubusercontent.com/24736423/76610461-d96e7b80-6510-11ea-9657-f8ba95ae388f.png"> |
=> Fix item's headerDate

react/components/atoms/button-tab-text/button-tab-text.js, react/components/atoms/button-tab-text/button-tab-text.stories.js, react/components/molecules/tabs-text/tabs-text.js, react/components/molecules/tabs-text/tabs-text.stories.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-react-native/issues/120 |
| Decisions | • Added variant prop to `TabsText` and `ButtonTabText` components <br>• `TabsText` and `ButtonTabText` components now support `compact` variant <br>• Fixed missing `style` prop in `ButtonTabText` component |
| Animated GIF | ![RN-TabsText_variant_compact](https://user-images.githubusercontent.com/22588915/77445852-81275b80-6de5-11ea-9cb1-9635dec8b9dd.gif) |
=> #120 TabsText variant support

react/components/organisms/chat/chat.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-react-native/issues/128 |
| Decisions | Remove scroll action on chat input focus. Add scroll action on chat submit. |
| Animated GIF | ![eeeee](https://user-images.githubusercontent.com/24736423/78551685-ff302d00-77fd-11ea-93f9-36d6fe73b692.gif) |
=> #128 Chat: writing scrolls to the end

package.json, react/components/atoms/button-icon/button-icon.js, react/components/atoms/button-icon/button-icon.stories.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/149 |
| Dependencies | https://github.com/ripe-tech/ripe-components-react-native/pull/143 |
| Decisions | • Added prop `nativeFeedback`  to `ButtonIcon` to give the option to use native feedback<br>• This option was added because the some icons don't look good when using native feedback in Android. This happens because the icons we use are not squared, some have more height/width than others so they look like they have more/less padding around them. For instance, in the `RichTextInput`component, it looks better without the native feedback.<br>**With `nativeFeedback=true`:**<br>![with_feedback](https://user-images.githubusercontent.com/22588915/80234972-ebcfef00-8650-11ea-8132-af16d627cf23.gif)<br>**With …
=> #149 ButtonIcon component with native feedback

package.json, react/util/ui-utils.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/155 |
| Decisions | Using react-native-device-info to access the device info. This way it is possible to know if the device is a tablet.  |
=> #155: Device detection improvement

react/components/atoms/button-keyboard/button-keyboard.js, react/components/molecules/keyboard-numeric/keyboard-numeric.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/159 |
| Decisions | Fix keyboard spacing in tablets. |
| Screenshots | <img width="734" alt="Screenshot 2020-05-04 at 10 26 10" src="https://user-images.githubusercontent.com/25725586/80952602-d2b60380-8df1-11ea-8020-e7b5000b966d.png"><img width="272" alt="Screenshot 2020-04-30 at 13 27 20" src="https://user-images.githubusercontent.com/25725586/80710172-561be000-8ae6-11ea-8469-ffef88a5a43a.png"><img width="653" alt="Screenshot 2020-05-04 at 10 26 16" src="https://user-images.githubusercontent.com/25725586/80952574-c467e780-8df1-11ea-8dc5-aa2de7db5a7e.png">|
=> #159: Tablet keyboard 

react/components/molecules/key-values/key-values.js, react/components/molecules/key-values/key-values.stories.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/160 |
| Decisions | • Added the optinal boolean prop `twoColumns` to make `KeyValues` have two columns. In tablet it defaults too true <br>• Supports all of the `KeyValue` props |
| Animated GIF | **Two Columns in tablet:**<br>![RN-Key_values_only_two_columns](https://user-images.githubusercontent.com/22588915/80712980-a72dd300-8aea-11ea-9baf-644eda783a68.gif)<br>**The addition of all the KeyValue props, allowed to have pressable columns as an example:**<br>![RN-Key_values_support_for_more_props](https://user-images.githubusercontent.com/22588915/80711189-d98a0100-8ae7-11ea-8750-5e73576fb2a1.gif) |
=> #160 Key Values custom columns number

react/components/atoms/lightbox/lightbox.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-react-native/issues/150 |
| Dependencies | - |
| Decisions | The Lightbox component didn't had a button to close it once you had opened the component on iOS. Now we added a new button that will allow the users to use it to close the Lightbox. |
| Animated GIF | ![May-14-2020 14-47-47](https://user-images.githubusercontent.com/13239857/81942901-a3be3f80-95f2-11ea-9fad-476d6e0a6ddd.gif) |
=> #150 - Added button to close the light box

react/components/atoms/avatar/avatar.js, react/components/atoms/button-icon/button-icon.js, react/components/atoms/button-keyboard/button-keyboard.js, react/components/atoms/button-tab-text/button-tab-text.js, react/components/atoms/button-tab/button-tab.js, react/components/atoms/button/button.js, react/components/atoms/icon/icon.js, react/components/atoms/tag/tag.js, react/components/atoms/textarea/textarea.js, react/components/molecules/header/header.js, react/components/molecules/key-value/key-value.js, react/components/molecules/keyboard-numeric/keyboard-numeric.js, react/util/utils.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/197 |
| Decisions | Add test IDs to allow for faster and easier automated testing (IDs rather than XPath). For Android, the way Appium recommends to do so is through accessibility labels. |
=> Add test IDs

.github/workflows/main.yml, .travis.yml
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/peri-templating/issues/28#issuecomment-776878761 |
| Decisions | Remove node 11 from both the Github actions and the travis.yml files for all of the vue related repos. |
=> #28 Remove workflow for node 11

react/components/molecules/tabs-text/tabs-text.js
| - | - |
| --- | --- |
| Related issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/223 |
| Decisions | Use ScrollView as the parent component, Scroll behaviour only if overflow exists |
| Animated GIF | ![CNe5PaCj49 (2)](https://user-images.githubusercontent.com/8842023/112026945-9f29b800-8b2e-11eb-8024-461f081e2b94.gif) |
=> feat: add scroll behaviour to tabs text

react/components/atoms/button-tab-text/button-tab-text.js
| - | - |
| --- | --- |
| Descripton | Regression provoked by:  https://github.com/ripe-tech/ripe-components-react-native/pull/167 |
| Animated GIF | ![y9cD2gtewU](https://user-images.githubusercontent.com/8842023/115721911-63c11a00-a376-11eb-8173-956d7280b162.gif)|
=> Fix buttonTabText component with 'compact' variant

CHANGELOG.md, react/util/ui-utils.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/252  |
| Decisions | Picked when testing attach from the camera with a real device...Handle the different(https://www.npmjs.com/package/react-native-image-picker#the-response-object)) response object that comes from picking from the camera. This is not well specified in the docs |
=> fix: normalizeImages function handling of images coming from camera

CHANGELOG.md, react/components/organisms/chat/chat.js
| - | - |
| --- | --- |
| Decisions | This was originated by the breaking change made in https://github.com/ripe-tech/ripe-robin-revamp/pull/260. Now the library will always return an array as result, wich voids the necessity of normalising the response within an array |
| Animated GIF | Before https://user-images.githubusercontent.com/8842023/124160394-1eb31580-da94-11eb-9afd-8c0f920d2b97.MP4 <br> After https://user-images.githubusercontent.com/8842023/124161114-ed871500-da94-11eb-9d21-c8b57aadd2f3.mp4|
=> fix: onRichTextInputPhotoAdded function in chat component

CHANGELOG.md, react/components/organisms/chat/chat.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/pull/267#discussion_r659795083 |
| Decisions | • Add ScrollView `onScroll` event as a prop <br>• Add `onScrollBottom` prop that is triggered when the scroll reaches the bottom  |
=> #263 Add onScroll and onScrollBottom props

CHANGELOG.md, react/components/organisms/chat/chat.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/pull/267#issuecomment-866939952 |
| Decisions | Add `animateScrollToEnd` props that dictates if the chat scroll is/isn't animated |
**Animated:**
https://user-images.githubusercontent.com/22588915/123624942-1d20ed80-d807-11eb-87fb-2b20f2c0f7bb.mov
**Not animated:**
https://user-images.githubusercontent.com/22588915/123624938-1c885700-d807-11eb-83e0-656d7211a77d.mov
=> #263 Chat scroll animation as optional

react/components/molecules/key-values/key-values.js
| - | - |
| --- | --- |
| Issue | Originated from ripe-id-mobile profile view screen, where we don't want to show key values were the value is not set. |
| Decisions | Prop that allows not rendering key values whose values are not defined. |
=> feat: do not show key values with no value

CHANGELOG.md, react/components/atoms/avatar/avatar.js
| - | - |
| --- | --- |
| Issue | Originated from https://github.com/ripe-tech/ripe-id-mobile/issues/2 |
| Decisions | Allow update to the avatar image after first setup. Necessary when editing a profile picture, it should show the picture after the user chooses a new one. |
=> feat: avatar image update

package.json, react/components/molecules/key-value/key-value.js, react/util/ui-utils.js
| - | - |
| --- | --- |
| Decisions | - Add `toClipboard` based on the [ripe-components-vue's toClipboard](https://github.com/ripe-tech/ripe-components-vue/blob/c2abe5555da16bf0c3901f7e33136d43f6a4dec0/vue/mixins/clipboard.js#L3)<br> - The util `toClipboard` method will clean for duplicated code and imports for clipboard pages in ripe-robin implementation and others in the future. <br> - Passing `_key` and `value` args in `onPress` and `onLongPress` callbacks - this will simplify the process specially when having several key-value component elements and wanting to perform different action that depend on internal values -- please check the implementation of this in ripe-robin where instead of having to create 14 new methods for 14 different key-values, we can now handle everything in one …
=> Add key value improvement and clipboard util method

CHANGELOG.md, react/components/atoms/container-openable/container-openable.js
| - | - |
| --- | --- |
| Issue | Originated by https://github.com/ripe-tech/ripe-id-mobile/issues/3 |
| Decisions | Added props to control knob visibility and target opacity for the overlay animation. |
=> Feat: Knob and overlay opacity configuration

react/components/atoms/avatar/avatar.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Make font size and opacity container height smaller. |
| Animated GIF | ![image](https://user-images.githubusercontent.com/25725586/125098437-e7b1b500-e0ce-11eb-9bbc-b7245ee90145.png) |
=> fix: make text and opacity container smaller

react/components/atoms/icon/icon.js
| - | - |
| --- | --- |
| Decisions | - Add feature to allow icon component to render an SVG icon from a certain uri such as icon="http://thenewcode.com/assets/svg/accessibility.svg" but also allow project specific requires such as icon="require('./assets/icon.svg')" by using already imported module https://github.com/react-native-svg/react-native-svg#use-with-content-loaded-from-uri  |
=> Icon: Add icon sources through URI or local require

react/components/molecules/key-value/key-value.js, react/components/molecules/key-values/key-values.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/pull/274#issuecomment-876237799 |
| Decisions | - Add `longPressToClipboard` to allow copy to clipboard after long press event. |
=> Key values: prop to allow copy to clipboard on long press

react/components/molecules/select/select.js, react/components/molecules/select/select.stories.js
| - | - |
| --- | --- |
| Decisions | - Add select variant prop to allow the selection of square/round edges. |
=> Select: Add border radius variant

CHANGELOG.md, react/components/atoms/icon/icon.js
| - | - |
| --- | --- |
| Decisions | - Add option to receive imported icon directly from an external project. As in react native we can't do dynamic imports like `require(./${iconName}.svg)` it's beneficial to add more options to import icons in the icon component. Currently we have by icon name, URI link and application import. This will add the option to directly receive an icon from an external project. |
=> Icon: Add svg icon option

react/components/atoms/link/link.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | `Link.url` prop is not required. It defaults to the [`onPress` callback](https://github.com/ripe-tech/ripe-components-react-native/blob/master/react/components/atoms/link/link.js#L42) |
=> Fix: Link.url is not required

react/components/atoms/container-openable/container-openable.js
| - | - |
| --- | --- |
| Issue | Originated by https://github.com/ripe-tech/ripe-id-mobile/issues/3 |
| Decisions | New prop that controls whether the overlay is pressable to close the container |
=> Feat: Enable container openable overlay press by prop

react/components/molecules/input-animated/input-animated.js
| - | - |
| --- | --- |
| Issue | When using input animated with KeyboardAvoidingView, the keyboard would appear above the input. |
| Decisions | • Input animated translateY animation was causing problems with KeyboardAvoidingView logic of translating the view to not appear above input. By changing to marginTop, the problem was fixed. <br> • Adding paddingTop to the input allowed the keyboard to give spacing to the whole input and not cutting it in half. |
=> fix: input animated keyboard avoiding view problem fix

react/components/molecules/button-toggle/button-toggle.js, react/components/organisms/button-group/button-group.js
| - | - |
| --- | --- |
| Issue | From https://github.com/ripe-tech/ripe-id-mobile/issues/1#issuecomment-883464734, necessary to override the border radius of the flat variant. |
| Decisions | Allow override of button toggle style. |
=> feat: override button toggle style

react/components/atoms/input/input.js, react/components/molecules/input-animated/input-animated.js
| - | - |
| --- | --- |
| Issue | Originated by https://github.com/ripe-tech/ripe-id-mobile/issues/3 |
| Decisions | Added props to propagate the on submit action to react native's [TextInput#onSubmitEditing](https://reactnative.dev/docs/textinput#onsubmitediting) |
=> Feat: Add onSubmitEditing prop to Input and InputAnimated

react/components/atoms/button/button.js, react/components/molecules/button-toggle/button-toggle.js, react/components/molecules/card/card.js
| - | - |
| --- | --- |
| Issue | `capitalize` is no longer defined as a local util but in button component it is still being imported as such. |
| Decisions | - Move capitalize import to ripe-commons-native |
=> Button: fix util undefined import

CHANGELOG.md, react/components/molecules/select/select.js
| - | - |
| --- | --- |
| Issue | - Select left padding is not consistent with other components. |
| Decisions | - Adapt select's left padding to 15 pixels so it matches other components spacing scheme. |
=> Select: Adapt padding

react/components/molecules/date-input/date-input.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-id-mobile/issues/2#issuecomment-884857213 |
| Decisions | Date input spacing similar to input form and rename prop to make it similar to text input. |
| Animated GIF | ![image](https://user-images.githubusercontent.com/25725586/126640366-a4ffb7f4-ba08-474d-8350-951286ded718.png) |
=> fix: make date input spacing similar to input form and prop rename

react/components/atoms/textarea/textarea.js, react/components/organisms/form/form.js
| - | - |
| --- | --- |
| Issue | Known problem with multiline TexInput and keyboardAvoidingView. |
| Decisions | Fixes it with https://github.com/facebook/react-native/issues/16826#issuecomment-512111075 |
=> fix: keyboard avoiding view fix for ios with multiline input

react/components/organisms/listing/listing.js
| - | - |
| --- | --- 
| Decisions | - Reacting to refreshing state <br> - Add reverse and sort field props <br> - Adapt style to not include top padding by default. <br> - Only rending empty list if state is not loading or refreshing  |
=> Listing: small improvements

CHANGELOG.md, react/components/molecules/select/select.js
| - | - |
| --- | --- |
| Decisions | - Add missing right padding to select to account for the arrow icon space that is always present. |
=> Select: Add right padding to select

CHANGELOG.md, react/components/molecules/select/select.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-id-mobile/issues/5#issuecomment-888248323 - select touchable area is not properly covering the arrow icon. |
| Decisions | - Add component fix prop [fixAndroidTouchableBug](https://github.com/lawnstarter/react-native-picker-select/issues/354) |
=> Select: fix touchable area

CHANGELOG.md, react/components/organisms/listing/listing.js
| - | - |
| --- | --- |
| Decisions | - Add refreshing and loading props to toggle the visibility of such loading indicators. <br> - Add `onEndReachedThreshold` prop with no default value (undefined default value) so the threshold works similar to what we had before https://github.com/ripe-tech/ripe-robin-revamp/pull/285#issuecomment-888996058. <br> - Add `onFilter` callback prop as it can be useful to maintain a state of the current filter in the father component. <br> - Small cleanup |
=> Listing: set of improvements

react/components/molecules/select/select.js
| - | - |
| --- | --- |
| Decisions | - Fix warning in which width can be received as "100%" and could be a string and not just a number. |
=> Select: fix prop type

react/components/atoms/avatar/avatar.js
| - | - |
| --- | --- |
| Decisions | - Add `imageProps` prop so we can override React's [Image](https://reactnative.dev/docs/image) default behavior such as setting `fadeDuration: 0`. |
=> Avatar: add prop imageProps

CHANGELOG.md, react/components/atoms/button/button.js, react/components/organisms/profile/profile.js
| - | - |
| --- | --- |
| Issue |  |
| Decisions | - Support for left and right icon <br> - Support for left and right slots <br> - Support for alignment keywords similar to other components <br> - Support for style override <br><br> **Breaking changes**: <br> - Button prop `icon` and icon related props renamed to `leftIcon` and `left<X>` <br> - `Align` prop values changed from flex-box values to values like `left, right, center, spacing`. <br> **This will require changes to ripe-id-mobile login button and changes to ripe-robin-revamp** |
| Animated GIF | Style override example: <br> ![image](https://user-images.githubusercontent.com/25725586/128501675-347802ed-c4fe-4840-a31e-a808f802d8a6.png)|
=> feat: button support for left right icons and slots and style override

react/components/atoms/button/button.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/pull/296#discussion_r685023673 |
| Decisions | Use icon (instead of just leftIcon), so that the previous API is maintained. |
=> feat: add support for icon aliases to maintain same API

react/components/organisms/button-group/button-group.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | - Support for overriding the button inside button group <br>  - New props `variantActive` and `buttonActiveStyle`, allowing to set different style and variant when the button is selected (if the toggle behaviour is enabled). <br> - Fixes to button toggle style override <br> - Button group style override support. <br> No breaking changes. |
| Animated GIF | Override example, using custom `Button` and `variantActive`: <br> ![button-group-override](https://user-images.githubusercontent.com/25725586/128714384-8f692a15-f904-4c62-af47-ee153ac2bac7.gif)|
=> feat: support for different button on button group

react/components/organisms/button-group/button-group.js
| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | https://github.com/ripe-tech/ripe-components-react-native/pull/268 |
| Decisions | Support wrapping on button group buttons. |
| Animated GIF | <img width="621" alt="image" src="https://user-images.githubusercontent.com/25725586/128885495-27a1f27e-4711-4151-b793-6f40b93ed98c.png"><img width="321" alt="image" src="https://user-images.githubusercontent.com/25725586/128885576-6736bfde-1e53-41c0-bd80-010a2df9f463.png"> |
=> feat: allow wrap on button group buttons

react/components/atoms/button/button.js
| - | - |
| --- | --- |
| Decisions | - Improve button disabled style by setting the opacity to the button (like in ripe-white) instead of to the text container. <br> - Add `onLongPress` handler |
=> Button: improve button disabled style and onLongPress

react/components/molecules/keyboard/keyboard.js
| - | - |
| --- | --- |
| Decisions | - Using proper replace for extracting special chars as previously it was being extracted with regex and we were getting unicoded strigs of chars in case of special chars being unicode chars like emojis. |
=> Keyboard: special chars with emojis fix

react/components/atoms/button/button.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | The loading indicator by default still renders in the center (making the text disappear). Alternatively, `loadingPosition=left` and `loadingPosition=right` can be used to display the loading indicator at the left or right of the text, respectively. |
| Animated GIF |  ![button-loaders](https://user-images.githubusercontent.com/16060539/135624549-d849b2dd-3713-4303-a781-92094156ebee.gif) |
=> feat: button loading indicator position

CHANGELOG.md, react/components/organisms/profile/profile.js
| - | - |
| --- | --- |
| Issue | Issue pointed out by @joamag<br>![image](https://user-images.githubusercontent.com/25725586/151532042-9c218392-6a2c-4ff6-930b-c730aa1f03c7.png) |
| Decisions | - Applied `paddingHorizontal` to button group in profile component. |
| Animated GIF | ![image](https://user-images.githubusercontent.com/25725586/151532097-9bd15c5a-a35d-46a2-879b-b55cc31d0851.png)<br>![image](https://user-images.githubusercontent.com/25725586/151532138-3e3b82d4-39c6-4cf4-8856-1700d7eec431.png)|
=> fix: apply padding horizontal to button group in profile

CHANGELOG.md, react/components/atoms/button/button.js, react/components/molecules/key-values/key-values.js, react/components/organisms/profile/profile.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | -  * Added URL prefix for some fields of the profile component<br>- Made button horizontal padding similar to the key-value padding|
| Animated GIF | ![image](https://user-images.githubusercontent.com/25725586/151543696-44f93061-bd62-4ae2-a7ae-6a4871f66ccb.png)|
=> feat: add URL prefix to profile and made button padding similar to key-value

CHANGELOG.md, package.json, react/components/atoms/lightbox/lightbox.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-react-native/issues/286 |
| Decisions | Double-tap zoom <br> Pinch zoom <br> Translate to the "edge" while zoomed in <br>|
| Animated GIF | <br> IOS: <br> ![2P5v4m5Kna](https://user-images.githubusercontent.com/8842023/151563818-61198bb9-af0f-4bf8-a8e8-4345539a68b3.gif) <br> Android: <br> ![HfaiLkN0I1](https://user-images.githubusercontent.com/8842023/151953152-c1f82808-cbd7-4e28-95a0-cd726360522b.gif)|
=> #286: Support for modal-like image viewing and zooming

CHANGELOG.md, react/components/organisms/profile/profile.js
| - | - |
| --- | --- |
| Issue | Issue found by @joamag where the links in the profiles had misaligned text<br>![imagem](https://user-images.githubusercontent.com/25725586/152765964-b940ba70-8d2b-4bf2-aa59-db13c9ca3dbe.png)|
| Decisions | - Remove margin top only for iOS |
| Animated GIF | <img width="602" alt="imagem" src="https://user-images.githubusercontent.com/25725586/152765921-f61211ae-8d5b-4bc9-b94e-2088c01146f2.png">|
=> fix: remove margin top for some key values in profile

CHANGELOG.md, package.json
* Added `source` prop to `Lightbox`
* Added new variant to `TabsText` and `ButtonTabText` to reflect the new design - [ripe-robin-revamp/#315](https://github.com/ripe-tech/ripe-robin-revamp/issues/315)
* Scroll on tab selected in `TabsText` now tries to show all tabs next to the one selected - [ripe-robin-revamp/#315](https://github.com/ripe-tech/ripe-robin-revamp/issues/315)
* Remove margin for iOS for profile specific key values
* Box shadow mismatch between iOS and Android for `Item`
=> version: 0.16.0

.github/workflows/main.yml
| - | - |
| --- | --- |
| Issue | Fix failing CI |
| Decisions | - The error was only happening in node 15. Since it is not LTS and dependencies do not support it, it is better to be removed.<br>![imagem](https://user-images.githubusercontent.com/25725586/154065454-484439e1-714a-41da-bb2a-83218c1cd846.png) |
=> fix: remove node 15 from github workflow

CHANGELOG.md, react/components/molecules/chat-message/chat-message.js, react/components/molecules/item/item.js, react/components/molecules/key-values/key-values.js
| - | - |
| --- | --- |
| Issue | Several problems in tablet:<br>**inconsistent margin horizontal in tablet**<br>![imagem](https://user-images.githubusercontent.com/25725586/155307461-2f9c411e-30fa-43c0-abc7-b8f771e35a11.png)<br>**misaligned expand button in key-values**<br>![imagem](https://user-images.githubusercontent.com/25725586/155307524-cf29a76a-903e-424f-a199-81bbb02882f1.png)<br>**images are centered in chat**<br><img width="972" alt="imagem" src="https://user-images.githubusercontent.com/25725586/155307604-b02a6777-3345-4044-a621-71f3a5e00f54.png"> |
| Decisions | - Use the same horizontal margin in `Item` component as the one being used elsewhere - do not use %<br>- Center expand button in `KeyValue`<br>- Align images in chat to the left |
| Animated GIF | …
=> fix: set of fixes in several components

CHANGELOG.md, react/components/molecules/tabs/tabs.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-react-native/issues/301 |
| Decisions | - Use index of current route to choose the selected tab in `Tabs`|
=> fix: use index of current route to choose the selected tab in `Tabs`

CHANGELOG.md, react/components/atoms/image-loading/image-loading.js, react/components/atoms/image-loading/image-loading.stories.js, react/components/atoms/image-loading/index.js, react/components/atoms/index.js, react/components/atoms/lightbox/lightbox.js, react/components/molecules/chat-message/chat-message.js, react/components/organisms/chat/chat.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/337 |
| Decisions | - `ImageLoading` component, that shows a placeholder when the images is loading<br>- Does not show placeholder if image is already cached and contains a workaround for iOS to avoid flickering. |
| Animated GIF | ![image-placeholder-loading](https://user-images.githubusercontent.com/25725586/156029005-ec5d21d7-a9a9-4c70-ab3c-6111008722c9.gif)|
=> #337: Component that shows placeholder while image is loading - `ImageLoading`

CHANGELOG.md, package.json
* New component `ImageLoading` that shows a placeholder while the image is loading - [ripe-robin-revamp/#337](https://github.com/ripe-tech/ripe-robin-revamp/issues/337)
* Support `TouchableHighlight` use in `Touchable` if `underlayColor` is passed as prop
* Default to touchable with highlight when using variant `flat` of `ButtonToggle`
=> version: 0.20.0

CHANGELOG.md, react/components/atoms/lightbox/lightbox.js, react/components/molecules/chat-message/chat-message.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/347 |
| Decisions | - Tweak avatar positioning in `ChatMessage` to match new design |
| Animated GIF | Before:<br><img width="1081" alt="image" src="https://user-images.githubusercontent.com/25725586/158384887-ebf16783-9e0d-44f8-86f0-ae5487a3abe9.png"><br>Now:<br>![image](https://user-images.githubusercontent.com/25725586/158384816-0344063f-a9be-4227-92ce-44e346f3b67d.png)|
=> #347: Tweak avatar positioning in chat message to match new design

CHANGELOG.md, react/components/molecules/avatar-list/avatar-list.js, react/components/molecules/avatar-list/avatar-list.stories.js, react/components/molecules/avatar-list/index.js, react/components/molecules/chat-message/chat-message.js, react/components/molecules/chat-message/chat-message.stories.js, react/components/molecules/index.js, react/components/organisms/chat/chat.js, react/components/organisms/chat/chat.stories.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/347 |
| Decisions | - New component `AvatarList`<br>- Use `AvatarList` in `ChatMessage` and propagate props (`replies` and `repliesAvatatars`) through `Chat`. |
| Animated GIF |![avatar-list](https://user-images.githubusercontent.com/25725586/158801406-93e1ce57-2c1e-42bc-97f8-e9d0b38c8f37.gif)![cht-avatars](https://user-images.githubusercontent.com/25725586/158801409-41d7e60f-6df8-4237-81dd-26e95f673864.gif) |
=> #347: `AvatarList` component

CHANGELOG.md, react/components/atoms/tag/tag.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/316#issuecomment-1085554127 |
| Decisions | - Shows ellipsis in `Tag` instead of breaking text. Went with this approach since going with the one to switch the text was too complicated |
| Animated GIF | <img width="394" alt="imagem" src="https://user-images.githubusercontent.com/25725586/161251143-6e97590e-bd57-4402-af24-6c30a6c08a8e.png">|
=> #316: Tag does not allow text breaking

CHANGELOG.md, react/components/molecules/header/header.js
| - | - |
| --- | --- |
| Issue | Feedback given Tuesday |
| Decisions | - Make android touch feedback in header buttons round (like in other Android apps) |
https://user-images.githubusercontent.com/25725586/164052907-7768fbc8-8cb2-4eb8-bc09-0e7145f610bb.mp4
=> feat: round touch feedback for header buttons in Android

CHANGELOG.md, react/components/atoms/container-draggable/container-draggable.js, react/components/atoms/container-openable/container-openable.js
| - | - |
| --- | --- |
| Issue | Related to the scanning tags feature being developed in Robin (there is no issue) |
| Decisions | - Support for applying gesture handling in `ContainerOpenable` with  `ContainerDraggable` to the whole content, instead of just the header - contrable by the prop `panOnlyOnHeader` (default to `true`) |
=> feat: allow gesture movements on the whole container of `ContainerOpenable`

CHANGELOG.md, react/components/atoms/container-draggable/container-draggable.js, react/components/atoms/container-openable/container-openable.js
Reverts ripe-tech/ripe-components-react-native#323
=> Revert "feat: allow gesture movements on the whole container of `ContainerOpenable`"

CHANGELOG.md, react/components/atoms/container-draggable/container-draggable.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | - Support for applying gesture handling in `ContainerOpenable` with  `ContainerDraggable` to the whole content, instead of just the header - contrable by the prop `panOnlyOnHeader` (default to `true`) <br>- Prop that controls if the `ContainerOpenable` closes on tap |
=> feat: pan on whole content of ContainerOpenable

CHANGELOG.md, react/components/molecules/chat-message/chat-message.js
| - | - |
| --- | --- |
| Issue | Issue mentioned by @joamag  |
| Decisions | - Increase top padding in `ChatMessage` content to match the one in the chat |
| Animated GIF | Before:<br>![image](https://user-images.githubusercontent.com/25725586/166217628-109278a4-1a01-4b1f-b953-cfc4d9bb273f.png)<br>Now:<br><img width="392" alt="image" src="https://user-images.githubusercontent.com/25725586/166217599-b8a9d02b-7965-4103-8232-7cc82b08c323.png">|
=> fix: increase top padding in `ChatMessage` content

CHANGELOG.md, react/components/molecules/chat-message/chat-message.js
| - | - |
| --- | --- |
| Issue | Replies text was misaligned |
| Decisions | -- |
| Animated GIF | <img width="389" alt="image" src="https://user-images.githubusercontent.com/25725586/166270021-48c35371-fc6d-4d1e-8fc3-64fbb17430f0.png">|
=> fix: misalignment in replies text in `ChatMessage`

CHANGELOG.md, react/components/organisms/listing/listing.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/329 |
| Decisions | Placeholder opacity only changed after animation ends (it can't be done gradually/interpolated, so its either at the start or at the end of the animation). |
| Animated GIF | ![fix-placeholder-text-opacity](https://user-images.githubusercontent.com/16060539/166648649-7ddffb1c-2ee8-4d1b-908e-9009bf0b8040.gif) |
=> fix: placeholder text animation in listing search expand

CHANGELOG.md, react/components/organisms/listing/listing.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/360 |
| Decisions | - Add `renderContentRefreshing` prop to `Listing` allowing content override when refreshing |
=> #360 - Listing: add prop to override listing content when refreshing

CHANGELOG.md, package.json
* Add `textStyle` prop to `ToastMessage`
* Add border to `Search` component
* Add `renderContentRefreshing` prop to `Listing` allowing content override when refreshing - [ripe-robin-revamp/#360](https://github.com/ripe-tech/ripe-robin-revamp/issues/360)
* Add more styling props for `tabs`, `key-values` and `profile` components - [ripe-robin-revamp/#372](https://github.com/ripe-tech/ripe-robin-revamp/issues/372)
* Add node versions `17` and `18` to the Github workflow
* Increase top padding in `ChatMessage` content
* Fix misalignment in replies text in `ChatMessage`
* Fix the placeholder text appearance in search input expand animation - [ripe-robin-revamp/#329](https://github.com/ripe-tech/ripe-robin-revamp/issues/329)
* Fix problem with `@react-native-community/eslint-config@3.0.2` that …
=> version: 0.24.0

CHANGELOG.md, package.json
* Add details prop to `Profile` to override account profile details - [ripe-robin-revamp/#351](https://github.com/ripe-tech/ripe-robin-revamp/issues/351)
* Add more color scheme props to `Chat` and `Listing` components - [ripe-robin-revamp/#372](https://github.com/ripe-tech/ripe-robin-revamp/issues/372)
* Adapt to latest profile buttons design - [#392](https://github.com/ripe-tech/ripe-robin-revamp/issues/392)
=> version: 0.25.0 :rainbow: 

CHANGELOG.md, react/components/molecules/search/search.js
| - | - |
| --- | --- |
| Issue | Search input border color is not changing when it is focused as it is expected by the [design](https://www.figma.com/file/KVbltf1J5ezwoILkQSdqCw/RIPE-Robin---Public?node-id=1219%3A3569) |
| Decisions | - Changing search input border color and allowing for override style color to be passed from prop style. |
=> feat: using different border color when search input is focused

CHANGELOG.md, package.json
| - | - |
| --- | --- |
| Issue | - Build in Robin is not detecting `no-messages-animation.svga` file |
| Decisions | - Include svga files in `package.json` files list |
=> fix: include svga files

react/components/organisms/listing/listing.js
| - | - |
| --- | --- |
| Decisions | - Add guard to `flatListRef` as it in some moments is `undefined` and if we spam it fails |
=> fix: add guard to flatlist reference

CHANGELOG.md, package.json
* Add and adapt to use new prop `inputIOSStyle` to override `select` color in `listing`
=> version: 0.27.5 :rainbow: 

CHANGELOG.md, react/components/molecules/key-values/key-values.js, react/components/molecules/key-values/key-values.stories.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/330 |
| Decisions | - Add a section property with a `key` that will be the name of the sections and with its own key values |
| Animated GIF | ![gLM7WLkhth](https://user-images.githubusercontent.com/8842023/191701739-26141f2a-f7ab-40c4-b6e0-cf98bd8b7054.gif) |
=> feat: Add sections to `key-values` components

CHANGELOG.md, package.json, react/components/molecules/tabs/tabs.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/472 |
| Decisions | - Bump `react-native-safe-area-context` version <br> - Use `SafeAreaView` from `react-native-safe-area-context` instead. <br> - Add always padding edge in the bottom as a prop `edges` of `SafeAreaView`. |
=> #472 Fix tab visibility undesired extra padding

CHANGELOG.md, react/assets/icons/error.svg, react/assets/icons/spam.svg
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/464#issuecomment-1308983513 |
| Decisions | - Add color and stroke properties to the icons to overcome `pretty` running `svga` which simplifies the icon and removes the dots |
| Animated GIF | Please check in Github filechanges |
=> #464 Fix spam and error SVG icons

CHANGELOG.md, react/assets/icons/extra/send-alt.svg
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/464#issuecomment-1310493309 |
| Decisions | - Fix send-alt icon viewport and size |
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24736423/201166608-37e56c67-16c5-4117-9e44-207a02a05d9e.png) | ![image](https://user-images.githubusercontent.com/24736423/201166402-4a30f05c-c50d-48b9-9e9a-42b2262be308.png) |
=> #464 Fix send-alt icon

CHANGELOG.md, package.json
* Add pagination to `chat` by integrating the use of the `listing` component - [ripe-robin-revamp/#340](https://github.com/ripe-tech/ripe-robin-revamp/issues/340)
* Add and adapt to newest chat message placeholder refresh component - [ripe-robin-revamp/#340](https://github.com/ripe-tech/ripe-robin-revamp/issues/340)
* Small style improvements to be consistent with the original design
* Small change in the alias used in listing filter components - [ripe-robin-revamp/#340](https://github.com/ripe-tech/ripe-robin-revamp/issues/340)
* Fix tab visibility undesired extra padding - [ripe-robin-revamp/#472](https://github.com/ripe-tech/ripe-robin-revamp/issues/472])
* Fix spam and error icons - [ripe-robin-revamp/#464](https://github.com/ripe-tech/ripe-robin-revamp/issues/464)
* Fix send-alt icon …
=> chore: version 0.28.0 :rainbow: 

CHANGELOG.md, react/components/molecules/rich-textinput/rich-textinput.js, react/components/organisms/chat/chat.js
| - | - |
| --- | --- |
| Decisions | - Add `attachButtonsVisibility` prop to allow hiding attach buttons.  |
=> Chat improvement
